Enable strategies written directly in Python as an alt to engines. (duplicate)
ShailChoksi/lichess-bot pull request #304
Opened 2021-04-06 15:18 UTC by icecream17

Same as #187 but updated. 

Notable difference between this pr and #187 is that instead of a strategy function, you implement the whole class.
Which enables more functionality but takes more setup.

Adds docs folder (only 1 file)

Breaking change: Previously, if the protocol was not "xboard" it was assumed to be "uci".
But now if someone put something like "yci" it throws

2021-04-06 15:37 UTC, TheYoBots requested changes

2021-04-06 15:37 UTC, TheYoBots commented on docs/creating-a-custom-bot.md
> +# Creating a custom bot
Would be nice if this file is in the main README.md file. But make the change at own will.

2021-04-06 15:47 UTC, TheYoBots commented
Also maybe linking something that shows a bunch of strategies written in python would allow further usage of this ‘protocol’ and it won’t be less extensively used [referring to https://github.com/ShailChoksi/lichess-bot/pull/187#issuecomment-792349236]

2021-04-12 08:15 UTC, TheYoBots requested changes

2021-04-12 08:15 UTC, TheYoBots commented on engine_wrapper.py
> +        "    See docs/creating-a-custom-bot.md")
I think after the request I made, you had forgotten to change this line.

2021-04-14 12:25 UTC, TheYoBots commented
Does an engine have to be added for this to function? It would be nice if the engine was disabled all together, though I’m not sure of any way to do this.

2021-04-14 14:30 UTC, icecream17 commented
If there's not a bug, a class only has to implement `search` and extend `MinimalEngine`:

```py
# strategies.py
class ExampleEngine(MinimalEngine):
    pass

class RandomMove(ExampleEngine):
    def search(self, board, *args):
        return random.choice(list(board.legal_moves))
```

2021-04-14 16:18 UTC, MarkZH commented
> If there's not a bug, a class only has to implement `search` and extend `MinimalEngine`:
> 
> ```python
> # strategies.py
> class ExampleEngine(MinimalEngine):
>     pass
> 
> class RandomMove(ExampleEngine):
>     def search(self, board, *args):
>         return random.choice(list(board.legal_moves))
> ```
> 
> Although `MinimalEngine` itself sets `self.engine = self` because of some methods in `EngineWrapper`

`name()` needs to be overridden, too.

2021-05-09 02:57 UTC, ShailChoksi approved these changes

2021-05-09 02:57 UTC, merged