Test updates by playing a game
ShailChoksi/lichess-bot pull request #321
Opened 2021-05-09 17:28 UTC by AttackingOrDefending

This PR downloads SF and plays one game to test the update. It will only work if someone puts their token https://github.com/AttackingOrDefending/lichess-bot/blob/lichess-test/test_nothing.py#L27. I was thinking that ShailChoksi could make a new bot and put its token here so every PR will be tested by playing a game. Maybe I should reduce the time control (e.g. 0+1) so it doesn't use a lot of resources on Github.

2021-05-09 17:36 UTC, TheYoBots commented
Can `logger.info()` be used instead of `print()` (https://github.com/ShailChoksi/lichess-bot/commit/132ac8b7da12b9a1d856b342cb2b9f1184332153)

2021-05-09 18:06 UTC, MarkZH commented
It's a good idea to rename the file `test_nothing.py` since it now tests more than nothing.

2021-05-10 05:09 UTC, MarkZH commented on tests.py
> +copyfile('lichess-bot.py', 'lichess_bot.py')
Alternatively, you could do this:

    import importlib
    lichess_bot = importlib.import_module("lichess-bot")

This way, there's no extra file left over after the tests.

2021-05-10 15:21 UTC, AttackingOrDefending commented
TheYoBots made a new bot and provided the api token (https://github.com/AttackingOrDefending/lichess-bot/pull/1). Shall I use his token or will ShailChoksi make a new one (because they are the owner of lichess-bot)?

2021-05-11 13:12 UTC, AttackingOrDefending commented
pytest doesn't seem to end if there is a bug unless I use assert so I lowered the AI level and if SF doesn't win the AI it will be assumed that it is a bug (because lichess-bot will restart and will lose on time because of backoff). I don't know how to get the response with json (https://github.com/AttackingOrDefending/lichess-bot/blob/lichess-test/tests.py#L48) using https://lichess.org/api#operation/gamePgn. Does anyone know how I can get the output in json?

2021-05-17 15:13 UTC, TheYoBots requested changes

2021-05-17 15:13 UTC, TheYoBots commented on .github/workflows/python-build-rest.yml
> +name: Python Build
Could you change the name of either this workflow or the other? Maybe name this Python Build Rest and leave the other one as Python Build or leave this as Python Build and name the other workflow lichess-bot Build?

2021-05-17 15:50 UTC, TheYoBots commented
- ‘Code Errors’ isn’t honestly a suitable workflow name IMO. It doesn’t convey much. Maybe ‘Python Tests’ would make more sense as that workflow tests the python code.
- ‘Tests’ isn’t a great name too again for the same reason. Maybe ‘lichess-bot Build’ or ‘Python Run’?
- If you are changing the name of the workflows, do make sure to change the status badge too in the README.md file

2021-06-01 17:47 UTC, AttackingOrDefending commented
They can cheat but this is a BOT account. They can also post in a team chat but I think this can be stopped with the permissions of the token. They can play rated games and resign but this will get them banned and if we also get banned, we won't be able to play rated games, which will solve the problem. I can only see 2 problems:

1. Spamming the game chat (spectator and between the 2 players)
2. Automatically resigning every game so we can't test them

If the 2nd option happens we can make a new file for tests from github and have this file, so we can test this on our own computers (with our own token), so we would still have automated tests.

2021-07-07 14:40 UTC, AttackingOrDefending commented
I think I can change the code so it gets the token from environment secrets, so nobody would know the token apart from ShailChoksi. Github prevents secrets from being printed in the logs, but I can think of 2 ways for someone to get the token:

1. Print it with some changes (e.g. instaed of 'y4y278h' print 'y4y2-78h')
2. Send it to a website that stores it, so you can later get it.

The advantage is that we can see who made a PR that printed the token.
Shall I implement this change?

2021-07-18 15:08 UTC, AttackingOrDefending commented
I have already renamed the files in .github/workflows a few times but I don't really like the names. Does anyone have any good names for the files? I am think of renaming them from 'Python Build' to 'Build' and from 'Lichess Bot Build' to 'Test' (or 'Tests').

2021-10-02 09:40 UTC, AttackingOrDefending commented
I made a simple environment that tries to emulate lichess, so there is no need for a token (https://github.com/AttackingOrDefending/lichess-bot/tree/test-offline).

Pros:
- No token needed
- Can run offline

Cons:
- Doesn't test the functions in lichess.py because it replaces them
- It hasn't implemented every function in lichess.py (e.g. chat)

Note: If chat is implemented, we can add the script to send a chat command (e.g. eval) to the engine, so we can test the engine's response to commands. This can be done also for other functions.

Should I make a new PR with the new branch and close this one?

2022-02-06 10:28 UTC, AttackingOrDefending commented
Closing since #404 was merged.

2022-02-06 10:28 UTC, closed without merging