Thoroughly document config.yml in README
ShailChoksi/lichess-bot pull request #337
Opened 2021-05-18 23:25 UTC by MarkZH

Proof-reading, corrections, and suggestions for moving this somewhere else are welcome.

2021-05-19 06:24 UTC, TheYoBots requested changes

2021-05-19 06:24 UTC, TheYoBots commented on README.md
> +    3. `"homemade"` if you want to write your own engine in Python within lichess-bot. See **Creating a custom bot** below.
Could you link the Creating a custom bot part in markdown syntax? Like, `[**Creating a custom bot**](#creating-a-custom-bot)`

2021-05-19 06:24 UTC, TheYoBots commented on README.md
> +```
Over here as well as in lines 105, 113, 128, 137, 164, 172 and 181 of your branch could your change it to something like, “```yml”

2021-05-19 22:43 UTC, nkoppel commented on README.md
> +  - `disconnect_time`: How many seconds to wait after the bot makes a move for an opponent to make a move. If no move is made during the wait, disconnect from the gmae.
"gmae" at the end of this line is a typo

2021-10-04 15:42 UTC, AttackingOrDefending commented
Will you also add documentation for the sections added to config.yml in #382?

2021-10-05 11:35 UTC, MarkZH commented
@AttackingOrDefending I could, but I'm not familiar with how those options work. If you could write up what these options mean, I'll incorporate them as another commit to this PR. I'll handle formatting, too.

2021-10-08 15:43 UTC, AttackingOrDefending commented
Yes, they do. querypv always returns the same move, which is the best one (you can verify it with queryall), query best returns more than one move and query returns many moves (not sure if they are all).
You can verify this with:
https://www.chessdb.cn/cdb.php?action=querypv&board=rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR%20w%20KQkq%20-%200%201&json=1
https://www.chessdb.cn/cdb.php?action=querybest&board=rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR%20w%20KQkq%20-%200%201&json=1
https://www.chessdb.cn/cdb.php?action=query&board=rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR%20w%20KQkq%20-%200%201&json=1
https://www.chessdb.cn/cdb.php?action=queryall&board=rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR%20w%20KQkq%20-%200%201&json=1
I think you should also add chessdb as a source for egtb in line 72.

2021-10-08 16:32 UTC, MarkZH commented
Next draft completed.

2022-01-14 17:58 UTC, AttackingOrDefending approved these changes

2022-01-15 06:25 UTC, merged