More easy and Good to see(The code)
ShailChoksi/lichess-bot pull request #362
Opened 2021-06-26 17:03 UTC by TG-KRISH

I made some editing here
I think it's nice

2021-06-26 17:04 UTC, TG-KRISH reviewed
It will be nice

2021-06-26 19:11 UTC, ShailChoksi commented on README.md
> +- NOTE: You won't see this token again on Lichess, so try coping it!
`coping` -> `copying`

2021-06-26 21:18 UTC, icecream17 requested changes

2021-06-26 21:18 UTC, icecream17 commented on README.md
> +- Here is a video on how to install the bot: [click here](https://youtu.be/w-aJFk00POQ). Or you may proceed to the next steps.
```suggestion md
- Here is [a video on how to install the bot](https://youtu.be/w-aJFk00POQ). Or you may proceed to the next steps.
```

Noooo "click here" is bad for a11y
https://www.google.com/search?client=firefox-b-1-d&q=click+here
First result: https://www.w3.org/QA/Tips/noClickHere

2021-07-02 01:59 UTC, icecream17 commented on README.md
> +- Here is a video on how to install the bot: [click here](https://youtu.be/w-aJFk00POQ). Or you may proceed to the next steps.
Wait why is this resolved, this isn't fixed

2021-07-02 02:00 UTC, icecream17 commented
The code hasn't actually changed, so the problems are not resolved yet.

2021-07-06 13:01 UTC, TheYoBots commented
Do note that this pull request seems to be copying my pull request here https://github.com/ShailChoksi/lichess-bot/pull/336 Which had been made earlier.

2021-08-16 09:19 UTC, TG-KRISH commented
ok

2021-08-16 09:20 UTC, closed without merging